<?php
namespace whitemerry\phpkin;

/**
 * Class AnnotationBlock
 *
 * @author Piotr Bugaj <whitemerry@outlook.com>
 * @package whitemerry\phpkin
 */
class AnnotationBlock
{
    const TYPE_SERVER = 'server';
    const TYPE_CLIENT = 'client';

    /**
     * @var String[]
     */
    protected $values;

    /**
     * @var Endpoint
     */
    protected $endpoint;

    /**
     * @var int
     */
    protected $startTimestamp;

    /**
     * @var int
     */
    protected $endTimestamp;

    /**
     * AnnotationBlock constructor.
     * (Builds 2 annotations)
     *
     * @param $type string
     * @param $endpoint Endpoint
     * @param $startTimestamp int
     * @param $endTimestamp int
     */
    public function __construct($type, $endpoint, $startTimestamp, $endTimestamp)
    {
        $this->setValues($type);
        $this->setEndpoint($endpoint);
        $this->setTimestamp('startTimestamp', $startTimestamp);
        $this->setTimestamp('endTimestamp', $endTimestamp);
    }

    /**
     * Duration for span
     *
     * @return int
     */
    public function getDuration()
    {
        return $this->endTimestamp - $this->startTimestamp;
    }

    /**
     * Timestamp for span
     *
     * @return int
     */
    public function getStartTimestamp()
    {
        return $this->startTimestamp;
    }

    /**
     * AnnotationBlock to array
     *
     * @return array
     */
    public function toArray()
    {
        return [
            [
                'endpoint' => $this->endpoint->toArray(),
                'timestamp' => $this->startTimestamp,
                'value' => $this->values[0]
            ],
            [
                'endpoint' => $this->endpoint->toArray(),
                'timestamp' => $this->endTimestamp,
                'value' => $this->values[1]
            ]
        ];
    }

    /**
     * Valid type and set annotation types
     *
     * @param $type string
     *
     * @throws \InvalidArgumentException
     */
    protected function setValues($type) {
        if (!in_array($type, [static::TYPE_CLIENT, static::TYPE_SERVER])) {
            throw new \InvalidArgumentException('$type must be TYPE_CLIENT or TYPE_SERVER');
        }

        if ($type === static::TYPE_CLIENT) {
            $this->values = ['cr', 'cs'];
        } else {
            $this->values = ['ss', 'sr'];
        }
    }

    /**
     * Valid and set endpoint
     *
     * @param $endpoint Endpoint
     *
     * @throws \InvalidArgumentException
     */
    protected function setEndpoint($endpoint)
    {
        if (!($endpoint instanceof Endpoint)) {
            throw new \InvalidArgumentException('$endpoint must be instance of Endpoint');
        }

        $this->endpoint = $endpoint;
    }

    /**
     * Valid and set timestamp
     *
     * @param $field string
     * @param $timestamp int
     *
     * @throws \InvalidArgumentException
     */
    protected function setTimestamp($field, $timestamp)
    {
        if (!is_zipkin_timestamp($timestamp)) {
            throw new \InvalidArgumentException($field . ' must be generated by zipkin_timestamp()');
        }

        $this->{$field} = $timestamp;
    }
}